# Generated by Django 5.1.7 on 2025-03-19 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='xeroaccount',
            name='account_class',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='xeroaccount',
            name='add_to_watchlist',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='xeroaccount',
            name='has_attachments',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='xeroaccount',
            name='reporting_code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='xeroaccount',
            name='reporting_code_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='xeroaccount',
            name='status',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='xeroaccount',
            name='system_account',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='xeroaccount',
            name='updated_date_utc',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
