# Generated by Django 5.1.7 on 2025-03-19 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_xeroaccount_account_class_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='xeroaccount',
            name='updated_date_utc',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
