# Generated by Django 5.1.7 on 2025-03-19 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_xeroaccount_updated_date_utc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='xeroaccount',
            name='account_class',
        ),
        migrations.RemoveField(
            model_name='xeroaccount',
            name='add_to_watchlist',
        ),
        migrations.RemoveField(
            model_name='xeroaccount',
            name='bank_account_number',
        ),
        migrations.RemoveField(
            model_name='xeroaccount',
            name='bank_account_type',
        ),
        migrations.RemoveField(
            model_name='xeroaccount',
            name='currency_code',
        ),
        migrations.RemoveField(
            model_name='xeroaccount',
            name='description',
        ),
        migrations.RemoveField(
            model_name='xeroaccount',
            name='enable_payments',
        ),
        migrations.RemoveField(
            model_name='xeroaccount',
            name='has_attachments',
        ),
        migrations.RemoveField(
            model_name='xeroaccount',
            name='reporting_code',
        ),
        migrations.RemoveField(
            model_name='xeroaccount',
            name='reporting_code_name',
        ),
        migrations.RemoveField(
            model_name='xeroaccount',
            name='status',
        ),
        migrations.RemoveField(
            model_name='xeroaccount',
            name='system_account',
        ),
        migrations.RemoveField(
            model_name='xeroaccount',
            name='tax_type',
        ),
        migrations.RemoveField(
            model_name='xeroaccount',
            name='updated_date_utc',
        ),
    ]
