# Generated by Django 5.1.7 on 2025-03-18 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='XeroToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_token', models.TextField()),
                ('refresh_token', models.TextField()),
                ('id_token', models.TextField(blank=True, null=True)),
                ('expires_at', models.DateTimeField()),
            ],
        ),
    ]
